<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/HrSystem.Application/HrSystem.Application.csproj" />
    <ProjectReference Include="../../src/HrSystem.Domain/HrSystem.Domain.csproj" />
    <ProjectReference Include="../../src/HrSystem.Infrastructure/HrSystem.Infrastructure.csproj" />
  </ItemGroup>
</Project>
