name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet restore HrSystem.Backend.slnx
      - run: dotnet build HrSystem.Backend.slnx --configuration Release --no-restore
      - run: dotnet test HrSystem.Backend.slnx --configuration Release --no-build --verbosity normal
